name: Release WPF App and Docker Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-wpf:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Datenlotsen.WPF/Datenlotsen.WPF.csproj

      - name: Build WPF app
        run: dotnet publish Datenlotsen.WPF/Datenlotsen.WPF.csproj -c Release -o publish

      - name: Upload WPF artifact
        uses: actions/upload-artifact@v4
        with:
          name: Datenlotsen
          path: publish/**

  build-docker:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}-api
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ github.ref_name }}
            type=raw,value=latest
            type=sha,prefix=,format=short
          labels: |
            org.opencontainers.image.author=ibrahimogod
            org.opencontainers.image.maintainer=ibrahimogod
            org.opencontainers.image.title=Datenlotsen Inventory Management API
            org.opencontainers.image.description=Inventory Management service for Datenlotsen
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=${{ github.ref_name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Datenlotsen.InventoryManagement.API/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

  create-release:
    runs-on: windows-latest
    needs: [build-wpf, build-docker]
    steps:
      - name: Download published app artifact
        uses: actions/download-artifact@v4
        with:
          name: Datenlotsen
          path: ./release

      - name: Create ZIP of published app
        run: Compress-Archive -Path ./release/* -DestinationPath ${{ github.workspace }}/Datenlotsen.zip
        shell: pwsh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/Datenlotsen.zip
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## WPF Application Release
            Download the ZIP file below, extract it, and run `Datenlotsen.WPF.exe` to start the application.

            ## Docker Image
            The latest Docker image is available at:
            ```bash
            ghcr.io/${{ github.repository }}-api:latest
            ```
            ### Pull the Image
            ```bash
            docker pull ghcr.io/${{ github.repository }}-api:${{ github.ref_name }}
            ```
            ### Run the Container
            ```bash
            docker run -d \
              -p 5155:8080 \
              -e ASPNETCORE_ENVIRONMENT=Production \
              ghcr.io/${{ github.repository }}-api:${{ github.ref_name }}
            ```
            See the [README.md](https://github.com/${{ github.repository }}/blob/main/README.md) for more details.
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}