# This workflow builds the WPF app, creates an MSI installer using WiX Toolset, and publishes a GitHub release
name: Build and Release WPF MSI

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag (e.g., v1.0.0)'
        required: false
        type: string
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Datenlotsen.WPF/Datenlotsen.WPF.csproj

      - name: Publish WPF app
        run: dotnet publish Datenlotsen.WPF/Datenlotsen.WPF.csproj -c Release -f net8.0-windows

      - name: Download WiX Toolset
        run: choco install wixtoolset -y
        shell: powershell

      - name: Create MSI installer
        run: |
          candle.exe Datenlotsen.WPF/installer/Product.wxs -o publish/Product.wixobj
          light.exe publish/Product.wixobj -o publish/Datenlotsen.msi
        shell: cmd

      - name: Set Release Tag
        id: set_tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            if [ -z "${{ github.event.inputs.tag_name }}" ]; then
              echo "::error::You must provide a tag_name when running manually."
              exit 1
            fi
            echo "::set-output name=tag::${{ github.event.inputs.tag_name }}"
          else
            echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
          fi
        shell: bash

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: publish/Datenlotsen.msi
          tag_name: ${{ steps.set_tag.outputs.tag }}
          token: ${{ secrets.GH_PAT }}